export default {
    LAKEMANGA: 'LakeManga',
    HOME: 'Trang chủ',
    STORY_NEW: 'Truyện mới',
    STORY_COMPLETE: 'Đủ bộ',
    STORY_HOT: 'Truyện Hot',
    STORY: 'Truyện',
    DESCRIPTION: 'Mô tả',
    ALTERNATIVE: 'Tên khác',
    SHOW_MORE: 'Xem thêm',
    SHOW_LESS: 'Thu gọn',
    GENRES: 'Thể loại',
    AUTHOR: 'Tác giả',
    TRANSLATION_TEAM: 'Nhóm dịch',
    SOURCE: 'Nguồn',
    SOURCE_RAW: 'Nguồn RAW',
    STATUS: 'Tình trạng',
    VIEWS: 'Số lượt xem',
    VIEW: 'Lượt xem',
    LAST_UPDATED: 'Cập nhật',
    COUNT_BOOKMARK: 'Theo dõi',
    ON_GOGING: 'Đang tiến hành',
    ON_COMPLETE: 'Đã hoàn thành',
    ON_PENDING: 'Tạm ngưng',
    LIST_CHAPTER: 'Danh sách chương',
    LIST: 'Danh sách',
    CHAPTER: 'Chương',
    DATE_UPLOAD: 'Ngày đăng',
    STORY_LATEST_UPDATED: 'Truyện mới cập nhật',
    STORY_FEATURE: 'Truyện nổi bật',
    UPDATED: 'Cập nhật',
    NEXT_CHAPTER: 'Chap kế',
    PRE_CHAPTER: 'Chap trước',
    READ_MANGA_ONLINE: 'Đọc truyện tranh online',
    MANGA: 'Truyện tranh',
    SEARCH: 'Tìm kiếm',
    SEARCH_RESULT: 'Tìm thấy',
    KEYWORD: 'Từ khóa',
    TOTAL: 'Tổng',
    FAN_PAGE: 'Fan Page',
    READ_FIRST_CHAPTER: 'Xem từ đầu',
    READ_LAST_CHAPTER: 'Xem mới nhất',
}